### ISSUE TITLE
Tag h1 come titolo di ogni section

### ISSUE THREAD

**Issue by acavestro** [tecweb-codedeck/codedeck#1]
Validando l'index il software del W3C mi dice.

>Consider using the h1 element as a top-level heading only (all h1 elements are treated as top-level headings by many screen readers and other tools).

Qualcuno si ricorda cos'ha detto la Gaggi in merito?

**Comment by gpozzan** [comment]
Purtroppo non ricordo di preciso, però in generale l'impressione che ho ricavato dalle lezioni della Gaggi è che gli heading possano anche ricominciare per le varie sezioni. Quindi i vari article dovrebbero avere il loro <h1> ecc.
la prima risposta a questa domanda (http://stackoverflow.com/questions/7405282/how-to-properly-use-h1-in-html5) sembra confermare questa visione.

**Comment by acavestro** [comment]
Ha detto che l'importante e' non saltare tag. E si trova d'accordo con il suggerimento del validatore del W3C.

Quindi tanto vale seguirlo e mettere h2.
